//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string BACK_TAP_TEST = "back-tap-test";
        
        public const string RIGHT_BACK_TAP = "right-back-tap";
        
        public const string HEARTBEAT_AND_JUMPSCARES = "heartbeat_and_jumpscares";
        
        public const string JUMPSCARE_BACK = "jumpscare-back";
        
        public const string HEARTHUMP = "hearthump";
    }
}
